name: 🆕 New Invader
description: Report a new invader not yet in the database
title: "[New Invader] {INVADER_ID}"
labels: ["new-invader"]
body:
  - type: input
    id: invader_id
    attributes:
      label: Invader ID
      description: "The invader identifier (e.g. PA_1529, LDN_42)"
      placeholder: "PA_1529"
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: City
      description: "City code"
      placeholder: "PA"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - OK
        - Damaged
        - A little damaged
        - Destroyed
        - Hidden
        - Unknown
    validations:
      required: true

  - type: input
    id: points
    attributes:
      label: Points
      description: "Point value of the invader"
      placeholder: "50"
    validations:
      required: false

  - type: input
    id: latitude
    attributes:
      label: Latitude
      description: "GPS latitude"
      placeholder: "48.856614"
    validations:
      required: false

  - type: input
    id: longitude
    attributes:
      label: Longitude
      description: "GPS longitude"
      placeholder: "2.352222"
    validations:
      required: false

  - type: input
    id: accuracy
    attributes:
      label: GPS Accuracy
      description: "GPS accuracy in meters"
      placeholder: "±10"
    validations:
      required: false

  - type: input
    id: image_invader
    attributes:
      label: Image invader
      description: "URL of the invader photo"
      placeholder: "https://..."
    validations:
      required: false

  - type: input
    id: image_location
    attributes:
      label: Image location
      description: "URL of the location/street photo"
      placeholder: "https://..."
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Any additional information"
    validations:
      required: false
